config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /es|pt-BR/ do
    namespace :home do
      get 'welcome/index'
    end

    get 'change_language', to: 'users_backoffice#change_language', as: "change_language"

    namespace :users_backoffice do
      root to: "news#index"

      post 'accept_friend_request/:friend_id', to: 'friends#accept_friend_request', as: "accept_friend_request"
      post 'send_friend_request/:friend_id', to: 'friends#send_friend_request', as: "send_friend_request"

      delete 'undo_friendship/:friend_id', to: 'friends#undo_friendship', as: "undo_friendship"
      delete 'cancel_friend_request/:friend_id', to: 'friends#cancel_friend_request', as: "cancel_friend_request"

      resources :users
      resources :videos
      resources :news
    end

    namespace :admins_backoffice do
      root to: "admins#index"

      get 'welcome/index'
      get 'only_users', to: 'users#index_user'
      put 'ban_user/:id', to: 'users#ban_user'
      put 'remove_ban/:id', to: 'users#remove_ban', as: "remove_user_ban"

      get 'comments_by_user/:user_id', to: 'comments#comments_by_user', as: "get_comments"
      delete 'delete_comment/:id', to: 'comments#delete_comment', as: "delete_comment"

      resources :comments
      resources :users
      resources :tags
      resources :videos
      resources :news
    end

    devise_for :users, controllers: { sessions: 'users/sessions' }

    devise_scope :user do
      root to: "users/sessions#new"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  self.table_name = 'videos'

  has_many :tag_videos, class_name: 'TagVideo', dependent: :destroy
  has_many :tags, through: :tag_video, class_name: 'Tag', source: :tag, dependent: :destroy

  scope :not_excluded, -> { where(deleted: false); order(:id) }

  accepts_nested_attributes_for :tag_videos, allow_destroy: true
end

app/controllers/admins_backoffice/comments_controller.rb
class AdminsBackoffice::CommentsController < AdminsBackofficeController
  def index
    @users = User.where(is_admin: false).not_excluded
  end

  def comments_by_user
    @comments = Comment.where(user_id: params[:user_id], deleted: false).not_excluded
  end

  def delete_comment
    comment = Comment.not_excluded.find(params[:id])
    user_id = comment.user_id
    if comment.update_attribute(:deleted, true)
      redirect_to admins_backoffice_get_comments_path(user_id), notice: "Comentário apagado"
    end
  end
end

app/controllers/admins_backoffice/news_controller.rb
class AdminsBackoffice::NewsController < AdminsBackofficeController
  before_action :set_new, only: [:edit, :update, :destroy]

  def index
    @news = New.not_excluded
  end
  
  # GET /news/1
  def show
  end

  # GET /news/new
  def new
    @new = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  def create
    @new = New.new(new_params)
    if @new.save
      redirect_to admins_backoffice_news_index_path, notice: "Notícia cadastrada"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @new.update(new_params)
      redirect_to admins_backoffice_news_index_path, notice: "Notícia atualizada"
    else
      render :edit
    end
  end

  # DELETE /news/1
  def destroy
    @new.update_attribute(:deleted, true)
    redirect_to admins_backoffice_news_index_path, notice: "Notícia apagada"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_new
    @new = New.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def new_params
    params.fetch(:new).permit(:title, :description, :date_news,
                                  tag_news_attributes: [:id, :new_id, :tag_id, :_destroy])
  end
end

app/controllers/admins_backoffice/tags_controller.rb
class AdminsBackoffice::TagsController < AdminsBackofficeController
  before_action :set_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.not_excluded
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admins_backoffice_tags_path, notice: "Tag cadastrado"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @tag.update(tag_params)
      redirect_to admins_backoffice_tags_path, notice: "Tag atualizado"
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.update_attribute(:deleted, true)
    redirect_to admins_backoffice_tags_path, notice: "Tag apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.fetch(:tag).permit(:name, :description, :locale)
  end
end

app/controllers/admins_backoffice/users_controller.rb
class AdminsBackoffice::UsersController < AdminsBackofficeController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.where(is_admin: true).not_excluded
  end

  def index_user
    @users = User.where(is_admin: false).not_excluded
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admins_backoffice_users_path, notice: "User cadastrado"
    else
      render :new
    end
  end

  def ban_user
    user = User.find(params[:id]).update_column(:banned, true)
    if user
      redirect_to admins_backoffice_only_users_path
    end
  end

  def remove_ban
    user = User.find(params[:id]).update_column(:banned, false)
    if user
      redirect_to admins_backoffice_only_users_path
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @user.update(user_params)
      redirect_to edit_admins_backoffice_user_path, notice: "User atualizado"
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.update_attribute(:deleted, true)
    redirect_to admins_backoffice_only_users_path, notice: "User apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user).permit(:name, :email, :is_admin, :password)
  end
end

app/controllers/admins_backoffice/videos_controller.rb
class AdminsBackoffice::VideosController < AdminsBackofficeController
  before_action :set_video, only: [:edit, :update, :destroy]

  def index
    @videos = Video.not_excluded
  end

  # GET /videos/1
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admins_backoffice_videos_path, notice: "Video cadastrado"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @video.update(video_params)
      redirect_to admins_backoffice_videos_path, notice: "Video atualizado"
    else
      render :edit
    end
  end

  # DELETE /videos/1
  def destroy
    @video.update_attribute(:deleted, true)
    redirect_to admins_backoffice_videos_path, notice: "Video apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def video_params
    params.fetch(:video).permit(:url, :title, :description, :duration,
                                tag_videos_attributes: [:id, :video_id, :tag_id, :_destroy])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin
  layout 'admins_backoffice'

  def is_admin
    redirect_to(users_backoffice_news_index_path,
    notice: 'Necessário existir uma internação em aberto') unless current_user.is_admin
  end
end

app/controllers/users_backoffice/videos_controller.rb
class UsersBackoffice::VideosController < UsersBackofficeController
  def index
    @videos = Video.all
  end

  def edit
    @video = Video.find(params[:id])
    @comments = Comment.where(video_id: @video.id, locale: params[:locale]).order(created_at: :desc)
    @rating = Rating.where(user_id: current_user.id, video_id: @video.id).last

    create_comment params[:comments], @video.id
    create_rating params[:rating], @video.id
  end

  private

  def create_comment(comment, item_id)
    if comment.present? and comment != ''
      _comment = Comment.new({user_id: current_user.id, comment: comment, video_id: item_id, locale: params[:locale]})
      if _comment.save
        redirect_to edit_users_backoffice_video_path(item_id), notice: "Comentário cadastrado"
      end
    end
  end

  def create_rating(rating, item_id)
    if rating.present? and rating != ''
      _rating = Rating.new({user_id: current_user.id, rate: rating, video_id: item_id})
      if _rating.save
        redirect_to edit_users_backoffice_video_path(item_id), notice: "Avaliação cadastrada"
      end
    end
  end
end

app/views/admins_backoffice/videos/_form.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary">

          <div class="card-header">
            <h3 class="card-title"><%= t('video') %></h3>
          </div>

          <%= simple_nested_form_for([:admins_backoffice, video], url: video.new_record? ? admins_backoffice_videos_path : admins_backoffice_video_path(video)) do |f| %>
            <div class="card-body">

              <div class="form-group">
                <label><%= t('title') %></label>
                <%= f.input :title, label: false,
                            input_html: { class:"form-control", placeholder:"Enter title" } %>
              </div>

              <div class="form-group">
                <label><%= t('description') %></label>
                <%= f.input :description, label: false,
                            input_html: { class:"form-control", placeholder:"Enter description" } %>
              </div>

              <div class="form-group">
                <label>URL</label>
                <%= f.input :url, label: false,
                            input_html: { class:"form-control", placeholder:"Enter url" } %>
              </div>

              <div class="form-group">
                <label><%= t('duration') %></label>
                <%= f.input :duration, label: false,
                            input_html: { class:"form-control", placeholder:"Enter duration" } %>
              </div>

              <%= render 'admins_backoffice/videos/form/tags', f: f, video: video %>

            </div>

            <div class="card-footer">
              <button type="submit" class="btn btn-outline-success"><%= t('register') %></button>
            </div>


          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admins_backoffice/videos/edit.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('edit_video') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('edit_video') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<%= render 'form', video: @video %>

app/views/admins_backoffice/videos/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('videos') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('videos') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title"><%= t('videos') %></h3>

      <div class="card-tools">
        <%= link_to t('register'), new_admins_backoffice_video_path, class: 'btn btn-outline-success' %>
      </div>
    </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
        <tr>
          <th>ID</th>
          <th><%= t('title') %></th>
          <th><%= t('duration') %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @videos.each do |video| %>
          <tr>
            <td><%= video.id %></td>
            <td><%= video.title %></td>
            <td><%= "#{video.duration} min" %></td>
            <td>
              <%= link_to edit_admins_backoffice_video_path(video.id), class: 'btn btn-outline-primary' do %>
                <i class="fas fa-edit"></i> <%= t('edit') %>
              <% end %>
              <%= link_to admins_backoffice_video_path(video), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-outline-danger' do %>
                <i class="fas fa-trash"></i> <%= t('delete') %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>
</section>

app/views/admins_backoffice/videos/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('register_video') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('register_video') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<%= render 'form', video: @video %>