config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /es|pt-BR/ do
    namespace :home do
      get 'welcome/index'
    end

    get 'change_language', to: 'users_backoffice#change_language', as: "change_language"

    namespace :users_backoffice do
      root to: "news#index"

      post 'accept_friend_request/:friend_id', to: 'friends#accept_friend_request', as: "accept_friend_request"
      post 'send_friend_request/:friend_id', to: 'friends#send_friend_request', as: "send_friend_request"

      delete 'undo_friendship/:friend_id', to: 'friends#undo_friendship', as: "undo_friendship"
      delete 'cancel_friend_request/:friend_id', to: 'friends#cancel_friend_request', as: "cancel_friend_request"

      resources :users
      resources :videos
      resources :news
    end

    namespace :admins_backoffice do
      root to: "admins#index"

      get 'welcome/index'
      get 'only_users', to: 'users#index_user'
      put 'ban_user/:id', to: 'users#ban_user'
      put 'remove_ban/:id', to: 'users#remove_ban', as: "remove_user_ban"

      get 'comments_by_user/:user_id', to: 'comments#comments_by_user', as: "get_comments"
      delete 'delete_comment/:id', to: 'comments#delete_comment', as: "delete_comment"

      resources :comments
      resources :users
      resources :tags
      resources :videos
      resources :news
    end

    devise_for :users, controllers: { sessions: 'users/sessions' }

    devise_scope :user do
      root to: "users/sessions#new"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :new, class_name: 'New', required: false
  belongs_to :video, class_name: 'Video', required: false
  belongs_to :user, class_name: 'User'

  has_one :new, class_name: 'New'
  has_one :video, class_name: 'Video'

  scope :not_excluded, -> { where(deleted: false); order(:id) }
  scope :by_locale, -> (locale) { where(locale: locale) }
end

app/controllers/admins_backoffice/comments_controller.rb
class AdminsBackoffice::CommentsController < AdminsBackofficeController
  def index
    @users = User.where(is_admin: false).not_excluded
  end

  def comments_by_user
    @comments = Comment.where(user_id: params[:user_id], deleted: false).not_excluded
  end

  def delete_comment
    comment = Comment.not_excluded.find(params[:id])
    user_id = comment.user_id
    if comment.update_attribute(:deleted, true)
      redirect_to admins_backoffice_get_comments_path(user_id), notice: "Comentário apagado"
    end
  end
end

app/controllers/admins_backoffice/news_controller.rb
class AdminsBackoffice::NewsController < AdminsBackofficeController
  before_action :set_new, only: [:edit, :update, :destroy]

  def index
    @news = New.not_excluded
  end
  
  # GET /news/1
  def show
  end

  # GET /news/new
  def new
    @new = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  def create
    @new = New.new(new_params)
    if @new.save
      redirect_to admins_backoffice_news_index_path, notice: "Notícia cadastrada"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @new.update(new_params)
      redirect_to admins_backoffice_news_index_path, notice: "Notícia atualizada"
    else
      render :edit
    end
  end

  # DELETE /news/1
  def destroy
    @new.update_attribute(:deleted, true)
    redirect_to admins_backoffice_news_index_path, notice: "Notícia apagada"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_new
    @new = New.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def new_params
    params.fetch(:new).permit(:title, :description, :date_news,
                                  tag_news_attributes: [:id, :new_id, :tag_id, :_destroy])
  end
end

app/controllers/admins_backoffice/tags_controller.rb
class AdminsBackoffice::TagsController < AdminsBackofficeController
  before_action :set_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.not_excluded
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admins_backoffice_tags_path, notice: "Tag cadastrado"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @tag.update(tag_params)
      redirect_to admins_backoffice_tags_path, notice: "Tag atualizado"
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.update_attribute(:deleted, true)
    redirect_to admins_backoffice_tags_path, notice: "Tag apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.fetch(:tag).permit(:name, :description, :locale)
  end
end

app/controllers/admins_backoffice/users_controller.rb
class AdminsBackoffice::UsersController < AdminsBackofficeController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.where(is_admin: true).not_excluded
  end

  def index_user
    @users = User.where(is_admin: false).not_excluded
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admins_backoffice_users_path, notice: "User cadastrado"
    else
      render :new
    end
  end

  def ban_user
    user = User.find(params[:id]).update_column(:banned, true)
    if user
      redirect_to admins_backoffice_only_users_path
    end
  end

  def remove_ban
    user = User.find(params[:id]).update_column(:banned, false)
    if user
      redirect_to admins_backoffice_only_users_path
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @user.update(user_params)
      redirect_to edit_admins_backoffice_user_path, notice: "User atualizado"
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.update_attribute(:deleted, true)
    redirect_to admins_backoffice_only_users_path, notice: "User apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user).permit(:name, :email, :is_admin, :password)
  end
end

app/controllers/admins_backoffice/videos_controller.rb
class AdminsBackoffice::VideosController < AdminsBackofficeController
  before_action :set_video, only: [:edit, :update, :destroy]

  def index
    @videos = Video.not_excluded
  end

  # GET /videos/1
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admins_backoffice_videos_path, notice: "Video cadastrado"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @video.update(video_params)
      redirect_to admins_backoffice_videos_path, notice: "Video atualizado"
    else
      render :edit
    end
  end

  # DELETE /videos/1
  def destroy
    @video.update_attribute(:deleted, true)
    redirect_to admins_backoffice_videos_path, notice: "Video apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def video_params
    params.fetch(:video).permit(:url, :title, :description, :duration,
                                tag_videos_attributes: [:id, :video_id, :tag_id, :_destroy])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin
  layout 'admins_backoffice'

  def is_admin
    redirect_to(users_backoffice_news_index_path,
    notice: 'Necessário existir uma internação em aberto') unless current_user.is_admin
  end
end

app/views/admins_backoffice/comments/comments_by_user.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('comments') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('comments') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">CMNT</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>

    </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
        <tr>
          <th>ID</th>
          <th><%= t('user') %></th>
          <th><%= t('comment') %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.id %></td>
            <td><%= comment.user.name %></td>
            <td><%= comment.comment %></td>
            <td>
              <%= link_to admins_backoffice_delete_comment_path(comment.id), method: :delete, class: "btn btn-outline-danger" do %>
                <i class="fas fa-trash"></i> <%= t('delete_comment') %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>
</section>

app/views/admins_backoffice/comments/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('select_user') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('select_user') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title"><%= t('users').upcase %></h3>

      <div class="card-tools">
        <div class="card-tools">
          <%= link_to t('register'), new_admins_backoffice_user_path, class: 'btn btn-outline-success' %>
        </div>
      </div>
    </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
        <tr>
          <th>ID</th>
          <th><%= t('name') %></th>
          <th><%= t('email') %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td>
              <%= link_to admins_backoffice_get_comments_path(user.id), class: "btn btn-outline-primary" do %>
                <i class="fas fa-mouse-pointer"></i> <%= t('select') %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>