config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /es|pt-BR/ do
    namespace :home do
      get 'welcome/index'
    end

    get 'change_language', to: 'users_backoffice#change_language', as: "change_language"

    namespace :users_backoffice do
      root to: "news#index"

      post 'accept_friend_request/:friend_id', to: 'friends#accept_friend_request', as: "accept_friend_request"
      post 'send_friend_request/:friend_id', to: 'friends#send_friend_request', as: "send_friend_request"

      delete 'undo_friendship/:friend_id', to: 'friends#undo_friendship', as: "undo_friendship"
      delete 'cancel_friend_request/:friend_id', to: 'friends#cancel_friend_request', as: "cancel_friend_request"

      resources :users
      resources :videos
      resources :news
    end

    namespace :admins_backoffice do
      root to: "admins#index"

      get 'welcome/index'
      get 'only_users', to: 'users#index_user'
      put 'ban_user/:id', to: 'users#ban_user'
      put 'remove_ban/:id', to: 'users#remove_ban', as: "remove_user_ban"

      get 'comments_by_user/:user_id', to: 'comments#comments_by_user', as: "get_comments"
      delete 'delete_comment/:id', to: 'comments#delete_comment', as: "delete_comment"

      resources :comments
      resources :users
      resources :tags
      resources :videos
      resources :news
    end

    devise_for :users, controllers: { sessions: 'users/sessions' }

    devise_scope :user do
      root to: "users/sessions#new"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends, class_name: 'Friend'

  scope :no_banned, -> { where(banned: false) }
  scope :not_excluded, -> { where(deleted: false); order(:id) }
end

app/controllers/admins_backoffice/comments_controller.rb
class AdminsBackoffice::CommentsController < AdminsBackofficeController
  def index
    @users = User.where(is_admin: false).not_excluded
  end

  def comments_by_user
    @comments = Comment.where(user_id: params[:user_id], deleted: false).not_excluded
  end

  def delete_comment
    comment = Comment.not_excluded.find(params[:id])
    user_id = comment.user_id
    if comment.update_attribute(:deleted, true)
      redirect_to admins_backoffice_get_comments_path(user_id), notice: "Comentário apagado"
    end
  end
end

app/controllers/admins_backoffice/news_controller.rb
class AdminsBackoffice::NewsController < AdminsBackofficeController
  before_action :set_new, only: [:edit, :update, :destroy]

  def index
    @news = New.not_excluded
  end
  
  # GET /news/1
  def show
  end

  # GET /news/new
  def new
    @new = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  def create
    @new = New.new(new_params)
    if @new.save
      redirect_to admins_backoffice_news_index_path, notice: "Notícia cadastrada"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @new.update(new_params)
      redirect_to admins_backoffice_news_index_path, notice: "Notícia atualizada"
    else
      render :edit
    end
  end

  # DELETE /news/1
  def destroy
    @new.update_attribute(:deleted, true)
    redirect_to admins_backoffice_news_index_path, notice: "Notícia apagada"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_new
    @new = New.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def new_params
    params.fetch(:new).permit(:title, :description, :date_news,
                                  tag_news_attributes: [:id, :new_id, :tag_id, :_destroy])
  end
end

app/controllers/admins_backoffice/tags_controller.rb
class AdminsBackoffice::TagsController < AdminsBackofficeController
  before_action :set_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.not_excluded
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admins_backoffice_tags_path, notice: "Tag cadastrado"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @tag.update(tag_params)
      redirect_to admins_backoffice_tags_path, notice: "Tag atualizado"
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.update_attribute(:deleted, true)
    redirect_to admins_backoffice_tags_path, notice: "Tag apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.fetch(:tag).permit(:name, :description, :locale)
  end
end

app/controllers/admins_backoffice/users_controller.rb
class AdminsBackoffice::UsersController < AdminsBackofficeController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.where(is_admin: true).not_excluded
  end

  def index_user
    @users = User.where(is_admin: false).not_excluded
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admins_backoffice_users_path, notice: "User cadastrado"
    else
      render :new
    end
  end

  def ban_user
    user = User.find(params[:id]).update_column(:banned, true)
    if user
      redirect_to admins_backoffice_only_users_path
    end
  end

  def remove_ban
    user = User.find(params[:id]).update_column(:banned, false)
    if user
      redirect_to admins_backoffice_only_users_path
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @user.update(user_params)
      redirect_to edit_admins_backoffice_user_path, notice: "User atualizado"
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.update_attribute(:deleted, true)
    redirect_to admins_backoffice_only_users_path, notice: "User apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user).permit(:name, :email, :is_admin, :password)
  end
end

app/controllers/admins_backoffice/videos_controller.rb
class AdminsBackoffice::VideosController < AdminsBackofficeController
  before_action :set_video, only: [:edit, :update, :destroy]

  def index
    @videos = Video.not_excluded
  end

  # GET /videos/1
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admins_backoffice_videos_path, notice: "Video cadastrado"
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  def update
    if @video.update(video_params)
      redirect_to admins_backoffice_videos_path, notice: "Video atualizado"
    else
      render :edit
    end
  end

  # DELETE /videos/1
  def destroy
    @video.update_attribute(:deleted, true)
    redirect_to admins_backoffice_videos_path, notice: "Video apagado"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def video_params
    params.fetch(:video).permit(:url, :title, :description, :duration,
                                tag_videos_attributes: [:id, :video_id, :tag_id, :_destroy])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin
  layout 'admins_backoffice'

  def is_admin
    redirect_to(users_backoffice_news_index_path,
    notice: 'Necessário existir uma internação em aberto') unless current_user.is_admin
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:namee])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    if resource.is_admin
      admins_backoffice_users_path
    else
      users_backoffice_news_index_path
    end
  end

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_backoffice/users_controller.rb
class UsersBackoffice::UsersController < UsersBackofficeController
  def index
    @users = User.no_banned.to_ary
    @users.delete(current_user)
  end
end

app/views/admins_backoffice/users/_form.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary">

          <div class="card-header">
            <h3 class="card-title"><%= t('user') %></h3>
          </div>

          <%= simple_form_for([:admins_backoffice, user], url: user.new_record? ? admins_backoffice_users_path : admins_backoffice_user_path(user)) do |f| %>
            <div class="card-body">

              <div class="form-group">
                <label><%= t('name') %></label>
                <%= f.input :name, label: false,
                            input_html: { class:"form-control", placeholder:"Enter name" } %>
              </div>

              <div class="form-group">
                <label><%= t('email') %></label>
                <%= f.input :email, label: false,
                            input_html: { type:"email", class:"form-control", placeholder:"Enter email" } %>
              </div>

              <div class="form-group">
                <label><%= t('password') %></label>
                <%= f.input :password, label: false,
                            input_html: { type:"password", class:"form-control", placeholder:"Enter password" } %>
              </div>

              <div class="form-check">
                <%= f.input :is_admin, label: false, as: :boolean, input_html: { type:"checkbox", class:"form-check-input" } %>
                <label class="form-check-label"><%= t('admin') %></label>
              </div>

            </div>

            <div class="card-footer">
              <button type="submit" class="btn btn-outline-success"><%= t('register') %></button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admins_backoffice/users/edit.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('edit_user') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('edit_user') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<%= render 'form', user: @user %>

app/views/admins_backoffice/users/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('admins') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('admins') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">ADMS</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
        <tr>
          <th>ID</th>
          <th><%= t('name') %></th>
          <th><%= t('email') %></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>
</section>

app/views/admins_backoffice/users/index_user.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('users') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('users') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title"><%= t('user').upcase %></h3>

      <div class="card-tools">
        <div class="card-tools">
          <%= link_to t('register'), new_admins_backoffice_user_path, class: 'btn btn-outline-success' %>
        </div>
      </div>
    </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
        <tr>
          <th>ID</th>
          <th><%= t('name') %></th>
          <th><%= t('email') %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td>
              <% if user.banned %>
                <%= link_to admins_backoffice_remove_user_ban_path(user.id), method: :put, class: "btn btn-outline-warning" do %>
                  <i class="fas fa-user-slash"></i> <%= t('remove_ban') %>
                <% end %>
              <% else %>
                <%= link_to admins_backoffice_path(user.id), method: :put, class: "btn btn-outline-warning" do %>
                  <i class="fas fa-user-slash"></i> <%= t('ban') %>
                <% end %>
              <% end %>

              <%= link_to edit_admins_backoffice_user_path(user.id), class: "btn btn-outline-primary" do %>
                <i class="fas fa-edit"></i> <%= t('edit') %>
              <% end %>
              <%= link_to admins_backoffice_user_path(user), method: :delete, data: {confirm: 'Tem certeza?'}, class: 'btn btn-outline-danger' do %>
                <i class="fas fa-trash"></i> <%= t('delete') %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/admins_backoffice/users/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= t('register_user') %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#"><%= t('home') %></a></li>
          <li class="breadcrumb-item active"><%= t('register_user') %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<%= render 'form', user: @user %>